name: test
on: push
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-1604, ubuntu-1804, ubuntu-2004, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        arch: x64
    - run: luamake help
