name: test
on: push
jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
        arch: [x86, x64]
        exclude:
        - os: ubuntu
          arch: x86
        - os: macos
          arch: x86
    steps:
    - uses: actions/checkout@v1
    - uses: actboy168/setup-luamake@master
    - run: luamake help
